### ISSUE TITLE
deliver a better devX

### ISSUE THREAD

**Issue by charlesfrye** [the-full-stack/ask-fsdl#51]
the developer experience is just OK. let's make it awesome.

note: some of these are more suggestion than requirement

## Everywhere
- [ ] add some minimal tests
- [ ] formalize into a devcontainer so we can run on codespaces
  - [ ] configure linting better
  - [ ] improve Python environment setup -- `pyenv virtualenv` seems to be on the out, see [VS Code docs](https://code.visualstudio.com/docs/python/environments)
- [ ] modularize the Makefile into reusable scripts
- [ ] modularize the env? as it gets more complicated, will become necessary

### Modal
- [ ] use `modal serve` in development so that the backend endpoint isn't polluted -- also gets faster updates
  - [ ] consider making it "mandatory", ie set by the ENV=dev flag
- [ ] update the `debug` command to use `modal shell`

### MongoDB
- [ ] better handling of dev/prod database separation, #41
- [ ] better setup for ad hoc querying #42
- [ ] add QoL tooling for ad hoc work with JSON, e.g. `jq`
- [ ] write a notebook for expectation testing/data doc generation for the docstore
  - important: connect to vector index so that vector index exploration feeds nicely into it

### FastAPI
- [ ] Make sure we have a good Swagger UI
  - [ ] linking docs across multiple "apps", e.g. the `/` mount and the `/gradio` mount
- [ ] Look into QoL tools for FastAPI -- Postman? OpenAPI tooling?
- [ ] Review other best practices for FastAPI design, focused on DevX
- [ ] Improve the Gradio interface

### Testing
- [ ] Add a MockLLM that fits LangChain interface? #48
  - reduces costs for unit tests and non-e2e integration tests 
### Evaluation
- [ ] Try out AutoEvaluator
- [ ] Make at least one simple LLM evaluation test, e.g. "No relevant sources found" or questions about capabilities
- [ ] Automate ingress of emoji feedback, #47

### Tooling
- [ ] Vector index exploration in W&B, #5
- [ ] LangChain tracing for debugging

## Frontend
- [ ] Testing of Discord bot -- health check, maybe a query
- [ ] make the `/health` a "hidden command" so we can use it in prod
- [ ] look into `interactions` library for Discord to see if it's cleaner, especially for streaming responses
